name: case_study_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.2
  flutter_smart_dialog: ^4.9.8
  flutter_bloc: ^8.1.6
  pinput: ^5.0.0
  flutter_svg: ^2.0.10+1
  
  intl: ^0.19.0
  connectivity_plus: ^6.0.5
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Helvetica Now Display
      fonts:
        - asset: fonts/HelveticaNowDisplay-Light.ttf
          weight: 300
        - asset: fonts/HelveticaNowDisplay-LightIta.ttf
          style: italic
          weight: 300
        - asset: fonts/HelveticaNowDisplay-Regular.ttf
          weight: 400
        - asset: fonts/HelveticaNowDisplay-RegIta.ttf
          style: italic
          weight: 400
        - asset: fonts/HelveticaNowDisplay-Medium.ttf
          weight: 500
        - asset: fonts/HelveticaNowDisplay-MedIta.ttf
          style: italic
          weight: 500
        - asset: fonts/HelveticaNowDisplay-Bold.ttf
          weight: 600
        - asset: fonts/HelveticaNowDisplay-BoldIta.ttf
          style: italic
          weight: 600
        - asset: fonts/HelveticaNowDisplay-ExtraBold.ttf
          weight: 700
        - asset: fonts/HelveticaNowDisplay-ExtBdIta.ttf
          style: italic
          weight: 700
